// Lightweight country + region + compliance helpers.
// Used by AddLeadDialog, Composer, Leads, Dashboard.

export type Region =
  | "Europe"
  | "North America"
  | "United Kingdom"
  | "APAC"
  | "Latin America"
  | "Middle East & Africa"
  | "Oceania"
  | "Other";

export interface Country {
  code: string; // ISO-2
  name: string;
  region: Region;
  // Primary anti-spam / data-protection law for B2B email outreach.
  law: string;
  // Short, user-facing one-liner of what the law requires.
  lawSummary: string;
}

// Country-specific compliance overrides (rich detail for the most common markets).
const SPECIFIC: Record<string, { law: string; lawSummary: string }> = {
  DE: { law: "GDPR + ePrivacy/UWG", lawSummary: "Strict prior consent for B2B email; legitimate interest narrowly applied. Always include unsubscribe + identify sender." },
  FR: { law: "GDPR + LCEN", lawSummary: "B2B requires soft opt-in / professional context. Mandatory unsubscribe and clear identification." },
  ES: { law: "GDPR + LSSI-CE", lawSummary: "Consent or pre-existing relationship required. Include opt-out and identify the sender." },
  IT: { law: "GDPR + Codice Privacy", lawSummary: "Consent generally required. Document lawful basis + provide easy unsubscribe." },
  NL: { law: "GDPR + Telecommunications Act", lawSummary: "B2B soft opt-in allowed for similar products; always honour opt-out and identify sender." },
  SE: { law: "GDPR + Marketing Act", lawSummary: "B2B is opt-out friendly but still requires lawful basis + unsubscribe + sender identity." },
  IE: { law: "GDPR + ePrivacy Regs", lawSummary: "B2B permitted with legitimate interest; mandatory unsubscribe and physical address." },
  PL: { law: "GDPR", lawSummary: "Consent or legitimate interest, with documented lawful basis and easy opt-out." },
  BE: { law: "GDPR", lawSummary: "B2B email allowed with legitimate interest; clear identification + unsubscribe required." },
  CH: { law: "FADP / nFADP", lawSummary: "Similar to GDPR. Need lawful basis, transparency, and a working opt-out." },
  GB: { law: "UK GDPR + PECR", lawSummary: "B2B to corporate addresses allowed with legitimate interest; unsubscribe + sender identity mandatory." },
  US: { law: "CAN-SPAM Act", lawSummary: "Truthful headers, no deceptive subject lines, valid physical postal address, and a working unsubscribe processed within 10 business days." },
  CA: { law: "CASL", lawSummary: "Express or implied consent required. Identify yourself, include physical address, and provide an unsubscribe mechanism." },
  MX: { law: "LFPDPPP", lawSummary: "Provide a privacy notice; honour ARCO + opt-out requests promptly." },
  AU: { law: "Spam Act 2003", lawSummary: "Consent (express or inferred), accurate sender identification, and a functional unsubscribe." },
  NZ: { law: "Unsolicited Electronic Messages Act", lawSummary: "Consent required; clear sender identification + working unsubscribe." },
  IN: { law: "DPDP Act 2023", lawSummary: "Consent + notice required; honour withdrawal of consent and grievance requests." },
  SG: { law: "PDPA + Spam Control Act", lawSummary: "Include unsubscribe, identify sender, and respect Do-Not-Call / opt-out registers." },
  JP: { law: "Act on Specified Commercial Transactions", lawSummary: "Opt-in required for most marketing; sender identity + unsubscribe mandatory." },
  HK: { law: "PDPO + UEMO", lawSummary: "Provide unsubscribe, accurate sender info, and respect opt-outs within 10 working days." },
  AE: { law: "PDPL (Federal Decree-Law 45/2021)", lawSummary: "Consent + clear opt-out. Honour data-subject rights and identify sender." },
  ZA: { law: "POPIA", lawSummary: "Consent or existing customer relationship; provide opt-out at every contact." },
  BR: { law: "LGPD", lawSummary: "Lawful basis + transparency. Provide privacy notice and honour data-subject rights." },
  AR: { law: "PDPL 25.326", lawSummary: "Consent generally required; provide opt-out and identify the sender." },
  // Additional rich coverage for major markets
  AT: { law: "GDPR + TKG", lawSummary: "B2B email needs prior consent or pre-existing customer relationship; unsubscribe mandatory." },
  DK: { law: "GDPR + Marketing Practices Act", lawSummary: "Consent generally required for B2B email; soft opt-in allowed for similar products." },
  FI: { law: "GDPR + Information Society Code", lawSummary: "B2B opt-out friendly; legitimate interest + unsubscribe + sender identity required." },
  NO: { law: "GDPR + Marketing Control Act", lawSummary: "Consent required for B2B unless existing relationship; clear unsubscribe and sender info." },
  PT: { law: "GDPR + Lei das Comunicações Eletrónicas", lawSummary: "Consent required; B2B legal-entity addresses allowed with opt-out." },
  GR: { law: "GDPR + Law 3471/2006", lawSummary: "Consent required for unsolicited email; clear opt-out mandatory." },
  CZ: { law: "GDPR + Act 480/2004", lawSummary: "Consent required; identify sender and offer unsubscribe in every message." },
  RO: { law: "GDPR + Law 506/2004", lawSummary: "Consent or existing relationship required; opt-out + sender identity mandatory." },
  HU: { law: "GDPR + Act XLVIII of 2008", lawSummary: "Prior consent required; honour opt-out promptly + identify sender." },
  BG: { law: "GDPR + Electronic Commerce Act", lawSummary: "Consent required; mandatory unsubscribe + sender identification." },
  LU: { law: "GDPR + Electronic Commerce Law", lawSummary: "B2B email allowed with legitimate interest; clear opt-out required." },
  IS: { law: "GDPR (EEA) + Act 90/2018", lawSummary: "Consent or legitimate interest; mandatory opt-out + sender identification." },
  LI: { law: "GDPR (EEA)", lawSummary: "Consent or legitimate interest; mandatory opt-out + sender info." },
  RU: { law: "Federal Law 152-FZ", lawSummary: "Consent required; data of Russian residents must be processed locally. Include opt-out." },
  UA: { law: "Law on Personal Data Protection", lawSummary: "Consent required; provide opt-out + sender identity." },
  TR: { law: "KVKK + Law on Electronic Commerce", lawSummary: "Prior consent required (IYS registration for commercial email); honour opt-out within 3 days." },
  IL: { law: "Communications Law (Spam Amendment)", lawSummary: "Opt-in required; sender identity + working unsubscribe + offence to send without consent." },
  SA: { law: "PDPL", lawSummary: "Consent required; identify sender, provide opt-out, and respect data-subject rights." },
  EG: { law: "Data Protection Law 151/2020", lawSummary: "Consent required; provide opt-out and identify sender." },
  NG: { law: "NDPA 2023", lawSummary: "Consent or legitimate interest; provide opt-out + sender identification." },
  KE: { law: "Data Protection Act 2019", lawSummary: "Consent required for direct marketing; offer opt-out at every contact." },
  KR: { law: "PIPA + Act on Promotion of Information and Communications", lawSummary: "Opt-in required for commercial email; '(광고)' prefix and unsubscribe mandatory." },
  CN: { law: "PIPL + Anti-Spam Regulations", lawSummary: "Consent required; cross-border transfer rules apply. Include opt-out + sender identity." },
  TW: { law: "PDPA", lawSummary: "Consent required for marketing; clear opt-out and sender identification." },
  TH: { law: "PDPA", lawSummary: "Consent or legitimate interest; provide privacy notice + opt-out." },
  ID: { law: "PDP Law 2022", lawSummary: "Consent required; honour data-subject rights + opt-out." },
  MY: { law: "PDPA 2010", lawSummary: "Consent required; sender identity + opt-out mandatory." },
  PH: { law: "Data Privacy Act 2012", lawSummary: "Consent required; provide opt-out + sender info." },
  VN: { law: "Decree 91/2020 on Anti-Spam", lawSummary: "Consent required; '[QC]' prefix on commercial email + opt-out." },
  CL: { law: "Law 19.628", lawSummary: "Consent required; provide opt-out and identify sender." },
  CO: { law: "Law 1581/2012", lawSummary: "Consent required; honour data-subject rights + opt-out." },
  PE: { law: "Law 29733", lawSummary: "Consent required for direct marketing; provide opt-out." },
  UY: { law: "Law 18.331", lawSummary: "Consent required; offer opt-out + sender info." },
};

// All ISO 3166-1 alpha-2 countries with their region for compliance grouping.
// Countries without a SPECIFIC entry get a sensible regional default.
const COUNTRY_NAMES: Array<[string, string, Region]> = [
  ["AF", "Afghanistan", "APAC"],
  ["AL", "Albania", "Europe"],
  ["DZ", "Algeria", "Middle East & Africa"],
  ["AS", "American Samoa", "Oceania"],
  ["AD", "Andorra", "Europe"],
  ["AO", "Angola", "Middle East & Africa"],
  ["AI", "Anguilla", "Latin America"],
  ["AG", "Antigua and Barbuda", "Latin America"],
  ["AR", "Argentina", "Latin America"],
  ["AM", "Armenia", "APAC"],
  ["AW", "Aruba", "Latin America"],
  ["AU", "Australia", "Oceania"],
  ["AT", "Austria", "Europe"],
  ["AZ", "Azerbaijan", "APAC"],
  ["BS", "Bahamas", "Latin America"],
  ["BH", "Bahrain", "Middle East & Africa"],
  ["BD", "Bangladesh", "APAC"],
  ["BB", "Barbados", "Latin America"],
  ["BY", "Belarus", "Europe"],
  ["BE", "Belgium", "Europe"],
  ["BZ", "Belize", "Latin America"],
  ["BJ", "Benin", "Middle East & Africa"],
  ["BM", "Bermuda", "North America"],
  ["BT", "Bhutan", "APAC"],
  ["BO", "Bolivia", "Latin America"],
  ["BA", "Bosnia and Herzegovina", "Europe"],
  ["BW", "Botswana", "Middle East & Africa"],
  ["BR", "Brazil", "Latin America"],
  ["BN", "Brunei", "APAC"],
  ["BG", "Bulgaria", "Europe"],
  ["BF", "Burkina Faso", "Middle East & Africa"],
  ["BI", "Burundi", "Middle East & Africa"],
  ["CV", "Cabo Verde", "Middle East & Africa"],
  ["KH", "Cambodia", "APAC"],
  ["CM", "Cameroon", "Middle East & Africa"],
  ["CA", "Canada", "North America"],
  ["KY", "Cayman Islands", "Latin America"],
  ["CF", "Central African Republic", "Middle East & Africa"],
  ["TD", "Chad", "Middle East & Africa"],
  ["CL", "Chile", "Latin America"],
  ["CN", "China", "APAC"],
  ["CO", "Colombia", "Latin America"],
  ["KM", "Comoros", "Middle East & Africa"],
  ["CG", "Congo", "Middle East & Africa"],
  ["CD", "Congo (DRC)", "Middle East & Africa"],
  ["CK", "Cook Islands", "Oceania"],
  ["CR", "Costa Rica", "Latin America"],
  ["CI", "Côte d'Ivoire", "Middle East & Africa"],
  ["HR", "Croatia", "Europe"],
  ["CU", "Cuba", "Latin America"],
  ["CW", "Curaçao", "Latin America"],
  ["CY", "Cyprus", "Europe"],
  ["CZ", "Czechia", "Europe"],
  ["DK", "Denmark", "Europe"],
  ["DJ", "Djibouti", "Middle East & Africa"],
  ["DM", "Dominica", "Latin America"],
  ["DO", "Dominican Republic", "Latin America"],
  ["EC", "Ecuador", "Latin America"],
  ["EG", "Egypt", "Middle East & Africa"],
  ["SV", "El Salvador", "Latin America"],
  ["GQ", "Equatorial Guinea", "Middle East & Africa"],
  ["ER", "Eritrea", "Middle East & Africa"],
  ["EE", "Estonia", "Europe"],
  ["SZ", "Eswatini", "Middle East & Africa"],
  ["ET", "Ethiopia", "Middle East & Africa"],
  ["FK", "Falkland Islands", "Latin America"],
  ["FO", "Faroe Islands", "Europe"],
  ["FJ", "Fiji", "Oceania"],
  ["FI", "Finland", "Europe"],
  ["FR", "France", "Europe"],
  ["GF", "French Guiana", "Latin America"],
  ["PF", "French Polynesia", "Oceania"],
  ["GA", "Gabon", "Middle East & Africa"],
  ["GM", "Gambia", "Middle East & Africa"],
  ["GE", "Georgia", "APAC"],
  ["DE", "Germany", "Europe"],
  ["GH", "Ghana", "Middle East & Africa"],
  ["GI", "Gibraltar", "Europe"],
  ["GR", "Greece", "Europe"],
  ["GL", "Greenland", "Europe"],
  ["GD", "Grenada", "Latin America"],
  ["GP", "Guadeloupe", "Latin America"],
  ["GU", "Guam", "Oceania"],
  ["GT", "Guatemala", "Latin America"],
  ["GG", "Guernsey", "Europe"],
  ["GN", "Guinea", "Middle East & Africa"],
  ["GW", "Guinea-Bissau", "Middle East & Africa"],
  ["GY", "Guyana", "Latin America"],
  ["HT", "Haiti", "Latin America"],
  ["HN", "Honduras", "Latin America"],
  ["HK", "Hong Kong", "APAC"],
  ["HU", "Hungary", "Europe"],
  ["IS", "Iceland", "Europe"],
  ["IN", "India", "APAC"],
  ["ID", "Indonesia", "APAC"],
  ["IR", "Iran", "Middle East & Africa"],
  ["IQ", "Iraq", "Middle East & Africa"],
  ["IE", "Ireland", "Europe"],
  ["IM", "Isle of Man", "Europe"],
  ["IL", "Israel", "Middle East & Africa"],
  ["IT", "Italy", "Europe"],
  ["JM", "Jamaica", "Latin America"],
  ["JP", "Japan", "APAC"],
  ["JE", "Jersey", "Europe"],
  ["JO", "Jordan", "Middle East & Africa"],
  ["KZ", "Kazakhstan", "APAC"],
  ["KE", "Kenya", "Middle East & Africa"],
  ["KI", "Kiribati", "Oceania"],
  ["KW", "Kuwait", "Middle East & Africa"],
  ["KG", "Kyrgyzstan", "APAC"],
  ["LA", "Laos", "APAC"],
  ["LV", "Latvia", "Europe"],
  ["LB", "Lebanon", "Middle East & Africa"],
  ["LS", "Lesotho", "Middle East & Africa"],
  ["LR", "Liberia", "Middle East & Africa"],
  ["LY", "Libya", "Middle East & Africa"],
  ["LI", "Liechtenstein", "Europe"],
  ["LT", "Lithuania", "Europe"],
  ["LU", "Luxembourg", "Europe"],
  ["MO", "Macao", "APAC"],
  ["MG", "Madagascar", "Middle East & Africa"],
  ["MW", "Malawi", "Middle East & Africa"],
  ["MY", "Malaysia", "APAC"],
  ["MV", "Maldives", "APAC"],
  ["ML", "Mali", "Middle East & Africa"],
  ["MT", "Malta", "Europe"],
  ["MH", "Marshall Islands", "Oceania"],
  ["MQ", "Martinique", "Latin America"],
  ["MR", "Mauritania", "Middle East & Africa"],
  ["MU", "Mauritius", "Middle East & Africa"],
  ["YT", "Mayotte", "Middle East & Africa"],
  ["MX", "Mexico", "North America"],
  ["FM", "Micronesia", "Oceania"],
  ["MD", "Moldova", "Europe"],
  ["MC", "Monaco", "Europe"],
  ["MN", "Mongolia", "APAC"],
  ["ME", "Montenegro", "Europe"],
  ["MS", "Montserrat", "Latin America"],
  ["MA", "Morocco", "Middle East & Africa"],
  ["MZ", "Mozambique", "Middle East & Africa"],
  ["MM", "Myanmar", "APAC"],
  ["NA", "Namibia", "Middle East & Africa"],
  ["NR", "Nauru", "Oceania"],
  ["NP", "Nepal", "APAC"],
  ["NL", "Netherlands", "Europe"],
  ["NC", "New Caledonia", "Oceania"],
  ["NZ", "New Zealand", "Oceania"],
  ["NI", "Nicaragua", "Latin America"],
  ["NE", "Niger", "Middle East & Africa"],
  ["NG", "Nigeria", "Middle East & Africa"],
  ["NU", "Niue", "Oceania"],
  ["KP", "North Korea", "APAC"],
  ["MK", "North Macedonia", "Europe"],
  ["NO", "Norway", "Europe"],
  ["OM", "Oman", "Middle East & Africa"],
  ["PK", "Pakistan", "APAC"],
  ["PW", "Palau", "Oceania"],
  ["PS", "Palestine", "Middle East & Africa"],
  ["PA", "Panama", "Latin America"],
  ["PG", "Papua New Guinea", "Oceania"],
  ["PY", "Paraguay", "Latin America"],
  ["PE", "Peru", "Latin America"],
  ["PH", "Philippines", "APAC"],
  ["PL", "Poland", "Europe"],
  ["PT", "Portugal", "Europe"],
  ["PR", "Puerto Rico", "North America"],
  ["QA", "Qatar", "Middle East & Africa"],
  ["RE", "Réunion", "Middle East & Africa"],
  ["RO", "Romania", "Europe"],
  ["RU", "Russia", "Europe"],
  ["RW", "Rwanda", "Middle East & Africa"],
  ["BL", "Saint Barthélemy", "Latin America"],
  ["KN", "Saint Kitts and Nevis", "Latin America"],
  ["LC", "Saint Lucia", "Latin America"],
  ["MF", "Saint Martin", "Latin America"],
  ["PM", "Saint Pierre and Miquelon", "North America"],
  ["VC", "Saint Vincent and the Grenadines", "Latin America"],
  ["WS", "Samoa", "Oceania"],
  ["SM", "San Marino", "Europe"],
  ["ST", "São Tomé and Príncipe", "Middle East & Africa"],
  ["SA", "Saudi Arabia", "Middle East & Africa"],
  ["SN", "Senegal", "Middle East & Africa"],
  ["RS", "Serbia", "Europe"],
  ["SC", "Seychelles", "Middle East & Africa"],
  ["SL", "Sierra Leone", "Middle East & Africa"],
  ["SG", "Singapore", "APAC"],
  ["SX", "Sint Maarten", "Latin America"],
  ["SK", "Slovakia", "Europe"],
  ["SI", "Slovenia", "Europe"],
  ["SB", "Solomon Islands", "Oceania"],
  ["SO", "Somalia", "Middle East & Africa"],
  ["ZA", "South Africa", "Middle East & Africa"],
  ["KR", "South Korea", "APAC"],
  ["SS", "South Sudan", "Middle East & Africa"],
  ["ES", "Spain", "Europe"],
  ["LK", "Sri Lanka", "APAC"],
  ["SD", "Sudan", "Middle East & Africa"],
  ["SR", "Suriname", "Latin America"],
  ["SE", "Sweden", "Europe"],
  ["CH", "Switzerland", "Europe"],
  ["SY", "Syria", "Middle East & Africa"],
  ["TW", "Taiwan", "APAC"],
  ["TJ", "Tajikistan", "APAC"],
  ["TZ", "Tanzania", "Middle East & Africa"],
  ["TH", "Thailand", "APAC"],
  ["TL", "Timor-Leste", "APAC"],
  ["TG", "Togo", "Middle East & Africa"],
  ["TO", "Tonga", "Oceania"],
  ["TT", "Trinidad and Tobago", "Latin America"],
  ["TN", "Tunisia", "Middle East & Africa"],
  ["TR", "Türkiye", "Middle East & Africa"],
  ["TM", "Turkmenistan", "APAC"],
  ["TC", "Turks and Caicos Islands", "Latin America"],
  ["TV", "Tuvalu", "Oceania"],
  ["UG", "Uganda", "Middle East & Africa"],
  ["UA", "Ukraine", "Europe"],
  ["AE", "United Arab Emirates", "Middle East & Africa"],
  ["GB", "United Kingdom", "United Kingdom"],
  ["US", "United States", "North America"],
  ["UY", "Uruguay", "Latin America"],
  ["UZ", "Uzbekistan", "APAC"],
  ["VU", "Vanuatu", "Oceania"],
  ["VA", "Vatican City", "Europe"],
  ["VE", "Venezuela", "Latin America"],
  ["VN", "Vietnam", "APAC"],
  ["VG", "British Virgin Islands", "Latin America"],
  ["VI", "U.S. Virgin Islands", "North America"],
  ["YE", "Yemen", "Middle East & Africa"],
  ["ZM", "Zambia", "Middle East & Africa"],
  ["ZW", "Zimbabwe", "Middle East & Africa"],
];

// Generic regional fallbacks for countries without a SPECIFIC entry.
const REGION_DEFAULT: Record<Region, { law: string; lawSummary: string }> = {
  Europe: {
    law: "GDPR / national ePrivacy",
    lawSummary: "Treat as GDPR territory: document a lawful basis, identify the sender, and include a working unsubscribe in every message.",
  },
  "United Kingdom": {
    law: "UK GDPR + PECR",
    lawSummary: "B2B to corporate addresses allowed with legitimate interest; unsubscribe + sender identity mandatory.",
  },
  "North America": {
    law: "Local anti-spam regulation",
    lawSummary: "Use truthful headers, a real physical address, and a working unsubscribe link.",
  },
  "Latin America": {
    law: "Local data protection law",
    lawSummary: "Most LATAM markets require consent or legitimate interest. Provide a privacy notice + opt-out.",
  },
  "Middle East & Africa": {
    law: "Local data protection law",
    lawSummary: "Many countries now require consent + opt-out. Identify yourself and honour data-subject requests.",
  },
  APAC: {
    law: "Local anti-spam / data law",
    lawSummary: "Most APAC markets require consent or legitimate interest. Always include a working unsubscribe + sender info.",
  },
  Oceania: {
    law: "Local anti-spam law",
    lawSummary: "Consent or pre-existing relationship typically required; sender identity + unsubscribe mandatory.",
  },
  Other: {
    law: "Best-practice anti-spam",
    lawSummary: "Always include sender identity, a real physical address, and a working unsubscribe.",
  },
};

export const COUNTRIES: Country[] = COUNTRY_NAMES
  .map(([code, name, region]) => {
    const specific = SPECIFIC[code];
    const fallback = REGION_DEFAULT[region];
    return {
      code,
      name,
      region,
      law: specific?.law ?? fallback.law,
      lawSummary: specific?.lawSummary ?? fallback.lawSummary,
    };
  })
  .sort((a, b) => a.name.localeCompare(b.name));

export function findCountry(code?: string | null): Country | undefined {
  if (!code) return undefined;
  return COUNTRIES.find((c) => c.code === code.toUpperCase());
}

export function regionOf(code?: string | null): Region | "Unknown" {
  return findCountry(code)?.region ?? "Unknown";
}

// Best-effort guess of country from an email address (TLD only).
const TLD_TO_CODE: Record<string, string> = {
  de: "DE", fr: "FR", es: "ES", it: "IT", nl: "NL", se: "SE", ie: "IE", pl: "PL",
  be: "BE", ch: "CH", uk: "GB", au: "AU", nz: "NZ", in: "IN", sg: "SG", jp: "JP",
  hk: "HK", ae: "AE", za: "ZA", br: "BR", ar: "AR", ca: "CA", mx: "MX", us: "US",
  at: "AT", dk: "DK", fi: "FI", no: "NO", pt: "PT", gr: "GR", cz: "CZ", ro: "RO",
  hu: "HU", bg: "BG", lu: "LU", is: "IS", ru: "RU", ua: "UA", tr: "TR", il: "IL",
  sa: "SA", eg: "EG", ng: "NG", ke: "KE", kr: "KR", cn: "CN", tw: "TW", th: "TH",
  id: "ID", my: "MY", ph: "PH", vn: "VN", cl: "CL", co: "CO", pe: "PE", uy: "UY",
};

export function guessCountryFromEmail(email?: string | null): string | undefined {
  if (!email) return undefined;
  const m = email.toLowerCase().match(/\.([a-z.]+)$/);
  if (!m) return undefined;
  const parts = m[1].split(".");
  // co.uk → uk, com.au → au
  const tld = parts[parts.length - 1];
  if (tld === "com" || tld === "org" || tld === "net" || tld === "io") return "US";
  return TLD_TO_CODE[tld];
}
